language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t bigluis/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bigluis/react-test npm test

after_success:
    - docker build -t bigluis/multi-client ./client
    - docker build -t bigluis/multi-nginx ./nginx
    - docker build -t bigluis/multi-server ./server
    - docker build -t bigluis/multi-worker ./worker
#Login to the docker client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
    - docker push bigluis/multi-client
    - docker push bigluis/multi-nginx
    - docker push bigluis/multi-server
    - docker push bigluis/multi-worker

on:
    branch: master